# Arrays

An array is a `special variable`, which can `hold more than one value` at a time. 
- All values in an array must be of the `same data type`;
- Elements of an array are stored in `contiguous memory locations`;
- Each element of an array has a `unique index`.

Python does not have a built-in support for arrays, but Python lists can be used instead. To implement arrays in Python, we can use the module `array` or the module `numpy`.

## Types of Arrays

### One Dimensional

A `one-dimensional array` is a data structure that contains a set of elements of the same data type. To access an element of an array, you use an index number. This specifies the position of the element in the array.

### Multi-Dimensional

The `2D array` is an array that is organized in rows and columns. We can identify each element in a 2D array using the position of rows and columns. For example, in a 3×3 2D array, the element in the second row and third column would be accessed using the indices (1, 2) or row 1, column 2.

A `3D array` is a multi-dimensional array(array of arrays). A 3D array is a collection of 2D arrays. It is specified by using three subscripts:Block size, row size and column size. More dimensions in an array means more data can be stored in that array.

## Arrays in Memory

### Why are Arrays of the same data type?

In Python arrays, elements are typically of the same data type for:

`Memory Efficiency`: Elements of the same data type enable a contiguous block of memory, making storage and access efficient;

`Efficient Operations`: Homogeneous data types allow for efficient element-wise operations;

`Performance Gains`: Similar data types enable CPU optimizations like SIMD for faster processing;

`Predictability`: Homogeneous arrays offer consistent and predictable behavior.

### 1D Array in Memory

In [ ]:
Memory Address:   1000    1004    1008    1012
NumPy Array:      [item1] [item2] [item3] [item4]

Arrays are typically stored as contiguous blocks of memory, and the elements in the array are of the same data type, ensuring efficient storage and operations.

### 2D Array in Memory

In [ ]:
Memory Address:   1000    1004    1008    1012    1016    1020    1024    1028    1032
NumPy Array:      [item1] [item2] [item3] [item4] [item5] [item6] [item7] [item8] [item8]
Rows:             0       0       0       1       1       1       2       2       2

![My Local Image](row-major-2D.png)


### 3D Array in Memory

![My Local Image](row-major-3D.png)

## Create an Array

### Using Array Module

In [16]:
import array

my_array = array.array('i', [])
my_array1 = array.array('i', [1, 2, 3, 4, 5])

print(my_array)
print(my_array1)

array('i')
array('i', [1, 2, 3, 4, 5])


### Using Numpy Module

In [8]:
import numpy as np

np_array = np.array([], dtype=int)
np_array1 = np.array([1, 2, 3, 4, 5], dtype=int)

print(np_array)
print(np_array1)

[]
[1 2 3 4 5]


### Time and Space Complexity of Arrays Defined in Array and Numpy Modules

#### Empty Array

The `time complexity is constant` O(1) because creating an empty array involves minimal operations, such as initializing the array metadata and allocating a minimal amount of memory for the array elements.

The `space complexity is` also `constant` O(1) because an empty array has no memory, therefore the memory allocated for the elements is minimal or none depending on the used module.

In [ ]:
# my_array = array.array('i', []) -----> O(1)
# np_array = np.array([], dtype=int) --> O(1)

#### Array with Elements

The `time complexity is linear` O(n), where n represents the number of elements in the array. The process of creating an array with elements involves copying the elements from the input iterable (in this case list) to the newly created array. As the number of elements increases, the time to copy the elements also increases.

The `space complexity is` also `linear` O(n), because as the number of elements increases, the memory allocated for the elements also increases.

In [ ]:
# my_array1 = array.array('i', [1, 2, 3, 4, 5]) -----> O(n)
# np_array1 = np.array([1, 2, 3, 4, 5], dtype=int) --> O(n)

## Insertion to Array

In [17]:
# Before insertion
print(my_array1)

my_array1.insert(5, 6)
# After insertion
print(my_array1)

# Even if you pass an index number that is higher than the maximum index in the existing array, the value will be inserted at the end.
my_array1.insert(100, 7)
print(my_array1)

array('i', [1, 2, 3, 4, 5])
array('i', [1, 2, 3, 4, 5, 6])
array('i', [1, 2, 3, 4, 5, 6, 7])


### Time and Space Complexity of Insertion to Array

`Time complexity` is `O(n)` because the worst-case scenario is that the element to be inserted is at the beginning of the array, and we need to shift all the elements to the right by one position.

`Space complexity` is `O(1)` because when inserting an element, only one place is needed.

## Traversal Operations

In [23]:
def traverseArray(input_array):
    for i in input_array:
        print(i)

traverseArray(my_array1)

1
2
3
4
5
6
7


### Time and Space Complexity of trasversal operations

In [24]:
# def traverseArray(input_array):
#     for i in input_array: -----> O(n)
#         print(i) --------------> O(1)

`Time complexity` is `O(n)`

`Space complexity` is `O(1)`

## Accessing Elements of an Array

In [39]:
def accessElement(input_array, index):
    max_index = len(input_array) - 1
    if index > max_index:
        print(f"Index does not exist! Maximum available index is {max_index}")
    else:
        return input_array[index]

accessElement(my_array1, 7)

Index does not exist! Maximum available index is 6


In [28]:
my_array1[-1:0:-1]

array('i', [7, 6, 5, 4, 3, 2])

### Time and Space Complexity of accessing elements of an array

In [ ]:
# def accessElement(input_array, index):
#     max_index = len(input_array) - 1 -----------------------------------------------> O(1)
#     if index > max_index: ----------------------------------------------------------> O(1)
#         print(f"Index does not exist! Maximum available index is {max_index}") -----> O(1)
#     else:
#         return input_array[index] --------------------------------------------------> O(1)

`Time complexity` is `O(1)`

`Space complexity` is `O(1)`

## Searching for an Element in an Array

In [56]:
def linear_search(input_array, element):
    for i in range(len(input_array)):
        if input_array[i] == element:
            return i
    return -1
        
print(linear_search(my_array1, 3))

2


### Time and Space Complexity of searching for an element in an array

In [ ]:
# def linear_search(input_array, element):
#     for i in range(len(input_array)): -----> O(n)
#         if input_array[i] == element: -----> O(1)
#             return i 
#     return -1

`Time complexity` is `O(n)`

`Space complexity` is `O(1)`

## Deleting an Element in an Array

In [59]:
# Before deletion
print(my_array1)

my_array1.remove(1)
# After deletion
print(my_array1)

array('i', [1, 2, 3, 4, 5, 6, 7])
array('i', [2, 3, 4, 5, 6, 7])


### Time and Space Complexity of deleting an element in an array

`Time complexity` is `O(n)`. If you delete the last element the time complexity will be O(1), because you don't need to shift any elements. If you remove the first element, you need to shift all the elements to the left by one position, so the time complexity will be O(n).

`Space complexity` is `O(1)`

## Time and Space Complexity of One Dimensional Array - Conclusion

| Operation | Time Complexity | Space Complexity |
| -------- | -------- | -------- |
| Creating an empty array           | O(1)        | O(1)        |
| Creating an array with elements   | O(N)        | O(N)        |
| Inserting a value in an array     | O(N)        | O(1)        |
| Traversing a given array          | O(N)        | O(1)        |
| Accessing a given cell            | O(1)        | O(1)        |
| Searching a given cell            | O(N)        | O(1)        |
| Deleting a given cell             | O(N)        | O(1)        |

## Create Two Dimensional Array

In [62]:
import numpy as np

twoDArray = np.array([[11, 15, 10, 6], [10, 14, 11, 5], [12, 17, 12, 8], [15, 18, 14, 9]])

print(twoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


### Time and Space Complexity of creating a two dimensional array

`Time complexity` is `O(mn)` or `O(1)` when the array is empty

`Space complexity` is `O(mn)` or `O(1)` when the array is empty

## Insertion to Two Dimensional Array

### Adding a Column

In [64]:
newTwoDArray = np.insert(twoDArray, 0, [[1, 2, 3, 4]], axis=1) # axis=1 adds column, axis=0 adds row

print(twoDArray)
print()
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]

[[ 1 11 15 10  6]
 [ 2 10 14 11  5]
 [ 3 12 17 12  8]
 [ 4 15 18 14  9]]


### Adding a Row

In [66]:
newTwoDArray = np.insert(twoDArray, 0, [[1, 2, 3, 4]], axis=0) # axis=1 adds column, axis=0 adds row

print(twoDArray)
print()
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]

[[ 1  2  3  4]
 [11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


In [67]:
newTwoDArray = np.append(twoDArray, [[1, 2, 3, 4]], axis=0) # append adds row or column (depending on the axis parameter) at the end of the 2D array

print(twoDArray)
print()
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]
 [ 1  2  3  4]]


### Time and Space Complexity of insertion to a two dimensional array

`Time complexity` is `O(mn)`

`Space complexity` is `O(mn)`

## Accessing Elements of a Two Dimensional Array

In [83]:
# Defining a function to access 2D array elements
def AccessArrayElements(array, rowIndex, columnIndex):
    if rowIndex >= len(array):
        print("Row index does not exist!")
    elif columnIndex >= len(array[0]):
        print("Column index does not exist!")
    else:
        return array[rowIndex][columnIndex]
    
AccessArrayElements(twoDArray, 1, 3)

5

### Time and Space Complexity of accessing elements of a two dimensional array

In [ ]:
# def AccessArrayElements(array, rowIndex, columnIndex):
#     if rowIndex >= len(array): --------------------------> O(1)
#         print("Row index does not exist!") --------------> O(1)
#     elif columnIndex >= len(array[0]): ------------------> O(1)
#         print("Column index does not exist!") -----------> O(1)
#     else:
#         return array[rowIndex][columnIndex] -------------> O(1)

`Time complexity` is `O(1)`

`Space complexity` is `O(1)`

## Traverse a Two Dimensional Array

In [91]:
def Traverse2DArray(array):
    for i in range(len(array)):
        for y in range(len(array[0])):
            print(array[i][y])

Traverse2DArray(twoDArray)

11
15
10
6
10
14
11
5
12
17
12
8
15
18
14
9


### Time and Space Complexity of traversing a two dimensional array

In [ ]:
# def Traverse2DArray(array):
#     for i in range(len(array)): ----------> O(m*n) for each row we are traversing all the columns
#         for y in range(len(array[0])): ---> O(n)
#             print(array[i][y]) -----------> O(1)

`Time complexity` is `O(n^2)`

`Space complexity` is `O(1)`

## Search for an Element in a Two Dimensional Array

In [99]:
print(twoDArray)

def findElementIn2DArray(array, element):
    for i in range(len(array)):
        for y in range(len(array[i])):
            if array[i][y] == element:
                return i, y
    print("Element not found")
            
findElementIn2DArray(twoDArray, 17)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]


(2, 1)

### Time and Space Complexity of searching for an element in a two dimensional array

In [ ]:
# def findElementIn2DArray(array, element):
#     for i in range(len(array)): -------------> O(n * m)
#         for y in range(len(array[i])): ------> O(n)
#             if array[i][y] == element: ------> O(1)
#                 return i, y -----------------> O(1)
#     print("Element not found") --------------> O(1)

`Time complexity` is `O(n^2)`

`Space complexity` is `O(1)`

## Delete an Element in a Two Dimensional Array

In [102]:
newTwoDArray = np.delete(twoDArray, 0, axis=1) # axis=1 deletes column, axis=0 deletes row

print(twoDArray)
print()
print(newTwoDArray)

[[11 15 10  6]
 [10 14 11  5]
 [12 17 12  8]
 [15 18 14  9]]

[[15 10  6]
 [14 11  5]
 [17 12  8]
 [18 14  9]]


### Time and Space Complexity of deleting an element in a two dimensional array

In [103]:
# newTwoDArray = np.delete(twoDArray, 0, axis=1) ---> O(n*m) where n is the number of rows and m is the number of columns. If you have the same number or rows and columns (as in this case), then it is quadratic time complexity O(n^2)

`Time complexity` is `O(n^2)`

`Space complexity` is `O(n^2)`

## Time and Space Complexity of Two Dimensional Array - Conclusion

| `Operation` | `Time Complexity` | `Space Complexity` |
| -------- | -------- | -------- |
| Creating an empty array               | O(1)        | O(1)        |
| Creating an array with elements       | O(mn)       | O(mn)       |
| Inserting a row/column in an array    | O(mn)       | O(mn)       |
| Traversing a given array              | O(mn)       | O(1)        |
| Accessing a given cell                | O(1)        | O(1)        |
| Searching a given cell                | O(mn)       | O(1)        |
| Deleting a row/column                 | O(mn)       | O(mn)       |

## When to use arrays

- Store multiple variables of same data type;

- Random access of elements using index.

## When to avoid arrays

- Same data type for all elements;

- Reserving more memory than required.